name: build push release image

on:
  push

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      
      # Checkout the repo, fetch-depth:0 to include tags
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Logout latest tag
        run: echo ${{ steps.previoustag.outputs.tag }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build latest and tagged release
        uses: docker/build-push-action@v2
        id: docker_build_master
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gsscogs/databaker:${{ steps.previoustag.outputs.tag }}
            gsscogs/databaker:latest
      - name: Master Image digest
        run: echo ${{ steps.docker_build_master.outputs.digest }}
