name: build push dev image amd64 (x64)

on:
  push:
    branches:
      - "test"

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dev
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: dev=true
          tags: |
            gsscogs/databaker:test

      - name: Develop Image digest
        run: echo ${{ steps.docker_build_dev.outputs.digest }}
